from __future__ import annotations

import json
import keyword
import re
from collections import OrderedDict
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any
from zipfile import ZipFile
from xml.etree import ElementTree as ET

AUTOGEN_START = "{# === BEGIN AUTOGENERATED: ip_adaptive_templates_docx === #}"
AUTOGEN_END = "{# === END AUTOGENERATED: ip_adaptive_templates_docx === #}"
GENERATED_PREFIX = "ip_adaptive_"

CATEGORY_FILE_MAP: dict[str, str] = {
    "01_minor_trach_laryngoscopy": "01_minor_trach_laryngoscopy.j2",
    "02_core_bronchoscopy": "02_core_bronchoscopy.j2",
    "03_navigation_robotic_ebus": "03_navigation_robotic_ebus.j2",
    "04_blvr_cryo": "04_blvr_cryo.j2",
    "05_pleural": "05_pleural.j2",
    "06_other_interventions": "06_other_interventions.j2",
    "07_clinical_assessment": "07_clinical_assessment.j2",
}

CATEGORY_DESCRIPTIONS: dict[str, str] = {
    "01_minor_trach_laryngoscopy": "Minor procedures, tracheostomy, and laryngoscopy",
    "02_core_bronchoscopy": "Core diagnostic and therapeutic bronchoscopy procedures",
    "03_navigation_robotic_ebus": "Navigation, robotic bronchoscopy, and EBUS procedures",
    "04_blvr_cryo": "BLVR and cryotherapy procedures",
    "05_pleural": "Pleural procedures",
    "06_other_interventions": "Other interventions",
    "07_clinical_assessment": "Clinical assessment and peri-procedural documentation",
}

SECTION_TO_CATEGORY: dict[int, str] = {
    1: "07_clinical_assessment",
    2: "07_clinical_assessment",
    3: "07_clinical_assessment",
    4: "02_core_bronchoscopy",
    5: "03_navigation_robotic_ebus",
    6: "03_navigation_robotic_ebus",
    7: "04_blvr_cryo",
    8: "04_blvr_cryo",
    9: "02_core_bronchoscopy",
    10: "01_minor_trach_laryngoscopy",
    11: "05_pleural",
    12: "06_other_interventions",
    13: "06_other_interventions",
    14: "07_clinical_assessment",
    15: "07_clinical_assessment",
}

MACRO_PREFERRED_SECTIONS = {4, 5, 6, 7, 8, 9, 10, 11, 12, 13}

HEADING1_RE = re.compile(r"^(?P<num>\d+)\.\s+(?P<title>.+?)\s*$")
HEADING2_RE = re.compile(r"^(?P<num>\d+\.\d+)\s+(?P<title>.+?)\s*$")
CPT_RE = re.compile(r"^CPT:\s*(?P<value>.+?)\s*$", re.IGNORECASE)

YES_NO_SET = {"yes", "no"}
STOPWORDS = {
    "a",
    "an",
    "and",
    "are",
    "as",
    "at",
    "be",
    "by",
    "for",
    "from",
    "in",
    "into",
    "is",
    "it",
    "its",
    "of",
    "on",
    "or",
    "that",
    "the",
    "their",
    "there",
    "to",
    "was",
    "were",
    "with",
}


@dataclass(frozen=True)
class DocParagraph:
    text: str
    style: str | None
    line_no: int


@dataclass
class ParamSpec:
    name: str
    kind: str
    explicit_blank: bool
    label: str


@dataclass
class AdaptiveField:
    raw: str
    kind: str
    options: list[str]
    explicit_blank: bool
    param_name: str


@dataclass
class ParagraphNode:
    source_text: str
    rendered_text: str
    fields: list[AdaptiveField] = field(default_factory=list)
    conditional_param: str | None = None


@dataclass
class TemplateBlock:
    section_number: int
    section_title: str
    block_number: str
    title: str
    category: str
    source_level: int
    macro_name: str
    slug: str
    raw_paragraphs: list[str] = field(default_factory=list)
    cpt_codes: list[str] = field(default_factory=list)
    instruction_notes: list[str] = field(default_factory=list)
    body_lines_raw: list[str] = field(default_factory=list)
    params: list[ParamSpec] = field(default_factory=list)
    nodes: list[ParagraphNode] = field(default_factory=list)

    def sort_key(self) -> tuple[int, ...]:
        pieces = []
        for token in self.block_number.split("."):
            if token.isdigit():
                pieces.append(int(token))
            else:
                pieces.append(999)
        return tuple(pieces)


@dataclass
class SectionNode:
    number: int
    title: str
    blocks: list[TemplateBlock] = field(default_factory=list)
    has_heading2: bool = False
    synthetic_counter: int = 1

    def next_synthetic_number(self) -> str:
        value = f"{self.number}.{self.synthetic_counter}"
        self.synthetic_counter += 1
        return value


@dataclass
class ParamOverrides:
    by_bracket: dict[str, str] = field(default_factory=dict)
    by_slug_bracket: dict[tuple[str, str], str] = field(default_factory=dict)
    by_slug_ordinal: dict[tuple[str, int], str] = field(default_factory=dict)


@dataclass
class CompilePlan:
    sections: list[SectionNode]
    macro_blocks: list[TemplateBlock]
    addon_blocks: list[TemplateBlock]


@dataclass
class CompileResult:
    changed_files: list[Path]
    generated_macro_count: int
    generated_addon_count: int
    planned_changes: dict[Path, str]


class CompilerError(RuntimeError):
    pass


def slugify(text: str) -> str:
    normalized = text.lower()
    normalized = normalized.replace("&", " and ")
    normalized = normalized.replace("%", " percent ")
    normalized = re.sub(r"[^a-z0-9]+", "_", normalized)
    normalized = re.sub(r"_+", "_", normalized).strip("_")
    if not normalized:
        return "x"
    if normalized[0].isdigit():
        normalized = f"x_{normalized}"
    return normalized


def _escape_single_quotes(text: str) -> str:
    return text.replace("\\", "\\\\").replace("'", "\\'")


def _read_json_or_yaml(path: Path) -> dict[str, Any]:
    text = path.read_text(encoding="utf-8")
    if not text.strip():
        return {}

    try:
        parsed = json.loads(text)
        return parsed if isinstance(parsed, dict) else {}
    except json.JSONDecodeError:
        pass

    try:
        import yaml  # type: ignore
    except Exception as exc:  # pragma: no cover - depends on env
        raise CompilerError(
            f"Override file exists at {path} but is not JSON and PyYAML is unavailable."
        ) from exc

    parsed_yaml = yaml.safe_load(text)
    return parsed_yaml if isinstance(parsed_yaml, dict) else {}


def load_param_overrides(path: Path) -> ParamOverrides:
    if not path.exists():
        return ParamOverrides()

    data = _read_json_or_yaml(path)
    overrides = ParamOverrides()

    by_bracket = data.get("by_bracket") or {}
    if isinstance(by_bracket, dict):
        for key, value in by_bracket.items():
            if isinstance(key, str) and isinstance(value, str) and value.strip():
                overrides.by_bracket[key.strip()] = slugify(value)

    by_slug_bracket = data.get("by_slug_bracket") or {}
    if isinstance(by_slug_bracket, dict):
        for key, value in by_slug_bracket.items():
            if not isinstance(value, str) or not value.strip():
                continue
            if not isinstance(key, str) or "::" not in key:
                continue
            slug, bracket = key.split("::", 1)
            overrides.by_slug_bracket[(slug.strip(), bracket.strip())] = slugify(value)

    by_slug_ordinal = data.get("by_slug_ordinal") or {}
    if isinstance(by_slug_ordinal, dict):
        for key, value in by_slug_ordinal.items():
            if isinstance(value, dict):
                slug = str(key).strip()
                for ordinal, name in value.items():
                    try:
                        idx = int(ordinal)
                    except Exception:
                        continue
                    if isinstance(name, str) and name.strip():
                        overrides.by_slug_ordinal[(slug, idx)] = slugify(name)
                continue

            if not isinstance(key, str) or ":" not in key:
                continue
            if not isinstance(value, str) or not value.strip():
                continue
            slug, ordinal = key.rsplit(":", 1)
            try:
                idx = int(ordinal)
            except ValueError:
                continue
            overrides.by_slug_ordinal[(slug.strip(), idx)] = slugify(value)

    templates_cfg = data.get("templates") or {}
    if isinstance(templates_cfg, dict):
        for slug, cfg in templates_cfg.items():
            if not isinstance(slug, str) or not isinstance(cfg, dict):
                continue

            bracket_map = cfg.get("brackets") or cfg.get("by_bracket") or {}
            if isinstance(bracket_map, dict):
                for bracket, name in bracket_map.items():
                    if isinstance(bracket, str) and isinstance(name, str) and name.strip():
                        overrides.by_slug_bracket[(slug, bracket.strip())] = slugify(name)

            ordinal_map = cfg.get("ordinals") or cfg.get("by_ordinal") or {}
            if isinstance(ordinal_map, dict):
                for ordinal, name in ordinal_map.items():
                    if not isinstance(name, str) or not name.strip():
                        continue
                    try:
                        idx = int(ordinal)
                    except Exception:
                        continue
                    overrides.by_slug_ordinal[(slug, idx)] = slugify(name)

    return overrides


def _iter_top_level_brackets(text: str) -> list[tuple[int, int, str]]:
    spans: list[tuple[int, int, str]] = []
    depth = 0
    start = -1
    for idx, char in enumerate(text):
        if char == "[":
            if depth == 0:
                start = idx
            depth += 1
            continue
        if char == "]":
            if depth == 0:
                continue
            depth -= 1
            if depth == 0 and start >= 0:
                inner = text[start + 1 : idx]
                spans.append((start, idx + 1, inner))
                start = -1
    return spans


def _normalize_bool_option(value: str) -> str:
    normalized = value.strip().lower()
    normalized = re.sub(r"[^a-z0-9\s]", "", normalized)
    return re.sub(r"\s+", " ", normalized).strip()


def _is_negation_pair(a: str, b: str) -> bool:
    a_norm = _normalize_bool_option(a)
    b_norm = _normalize_bool_option(b)
    if not a_norm or not b_norm:
        return False

    if {a_norm, b_norm} == YES_NO_SET:
        return True

    explicit_pairs = {
        ("has", "has not"),
        ("does", "does not"),
        ("was", "was not"),
        ("is", "is not"),
        ("is", "is no"),
        ("present", "absent"),
        ("with", "without"),
        ("ordered", "not indicated"),
        ("performed", "not performed"),
    }
    if (a_norm, b_norm) in explicit_pairs or (b_norm, a_norm) in explicit_pairs:
        return True

    if a_norm == f"not {b_norm}" or b_norm == f"not {a_norm}":
        return True
    if a_norm.replace(" not", "") == b_norm or b_norm.replace(" not", "") == a_norm:
        return True

    return False


def _bool_true_false(options: list[str]) -> tuple[str, str]:
    if len(options) != 2:
        return options[0], options[1]

    a, b = options[0].strip(), options[1].strip()
    a_norm = _normalize_bool_option(a)
    b_norm = _normalize_bool_option(b)

    if {a_norm, b_norm} == YES_NO_SET:
        return (a, b) if a_norm == "yes" else (b, a)

    if " not" in b_norm or b_norm.startswith("not "):
        return a, b
    if " not" in a_norm or a_norm.startswith("not "):
        return b, a

    if a_norm == "present" and b_norm == "absent":
        return a, b
    if b_norm == "present" and a_norm == "absent":
        return b, a

    return a, b


def classify_field(inner: str) -> tuple[str, list[str], bool]:
    raw = inner.strip()
    explicit_blank = "____" in raw

    if " / " in raw:
        options = [part.strip() for part in raw.split(" / ")]
    else:
        options = [raw]

    if len(options) == 2 and _is_negation_pair(options[0], options[1]):
        return "bool", options, explicit_blank

    if len(options) == 1:
        return "blank", options, explicit_blank

    return "enum", options, explicit_blank


def _clean_candidate_name(candidate: str) -> str:
    cleaned = candidate.strip().lower()
    if len(cleaned) > 80:
        return ""
    cleaned = cleaned.replace("other:", "")
    cleaned = cleaned.replace("other", "")
    cleaned = cleaned.replace("____", "")
    cleaned = cleaned.replace("%", " percent ")
    cleaned = re.sub(r"\([^)]*\)", " ", cleaned)
    cleaned = re.sub(r"[^a-z0-9\s_/:-]", " ", cleaned)
    cleaned = cleaned.replace("/", " ")
    cleaned = cleaned.replace(":", " ")
    cleaned = re.sub(r"\s+", " ", cleaned).strip()
    if not cleaned:
        return ""

    tokens = [token for token in cleaned.split() if token not in STOPWORDS and not token.isdigit()]
    if not tokens:
        return ""
    if any(len(token) > 20 for token in tokens):
        return ""
    return "_".join(tokens[:3])


def _is_reasonable_param_base(name: str) -> bool:
    if not name:
        return False
    if len(name) > 36:
        return False
    if name.count("_") > 3:
        return False
    return True


def _heuristic_from_context(context_before: str, context_after: str, paragraph_text: str) -> str:
    combined = f"{context_before} {context_after}".lower()

    if "due to" in context_before.lower():
        return "reason"

    if "hemithorax" in combined and ("right" in combined or "left" in combined):
        return "hemithorax_side"

    if "airway segment" in combined:
        return "airway_segment"

    if "station" in combined:
        return "station"

    if "lobe" in combined and "target" in combined:
        return "target_lobe"

    if "indication" in context_before.lower():
        return "indication"

    if "complications" in context_before.lower():
        return "complications"

    if "specimen" in context_before.lower():
        return "specimens"

    if "cxr ordered" in combined:
        return "cxr_ordered"

    if ":" in context_before:
        prefix = context_before.rsplit(":", 1)[0]
        clause = re.split(r"[.;\n]", prefix)[-1]
        candidate = _clean_candidate_name(clause)
        if candidate and _is_reasonable_param_base(candidate):
            return candidate

    tokens = re.findall(r"[A-Za-z0-9]+", context_before.lower())
    tokens = [token for token in tokens if token not in STOPWORDS and not token.isdigit()]
    if tokens:
        candidate = "_".join(tokens[-2:])
    else:
        candidate = ""
    if candidate and _is_reasonable_param_base(candidate):
        return candidate

    return ""


def _normalize_param_name(name: str) -> str:
    result = slugify(name)
    if keyword.iskeyword(result):
        result = f"{result}_value"
    return result


def _human_label(bracket_literal: str) -> str:
    label = bracket_literal.strip()[1:-1] if bracket_literal.startswith("[") else bracket_literal
    label = label.replace("____", "").strip()
    label = re.sub(r"\s+", " ", label)
    return label or "Field"


def _parse_cpt_codes(cpt_line: str) -> list[str]:
    value = cpt_line.strip()
    if "verify" in value.lower():
        return []
    codes = re.findall(r"\b\d{5}\b", value)
    deduped: list[str] = []
    seen: set[str] = set()
    for code in codes:
        if code in seen:
            continue
        seen.add(code)
        deduped.append(code)
    return deduped


def _is_doc_instruction(text: str) -> bool:
    return text.strip().startswith("▸ Document:")


def _extract_condition_prefix(text: str) -> tuple[str | None, str]:
    stripped = text.strip()
    if not stripped.startswith("["):
        return None, text

    spans = _iter_top_level_brackets(stripped)
    if not spans:
        return None, text

    start, end, inner = spans[0]
    if start != 0:
        return None, text

    inner_clean = inner.strip()
    if not inner_clean.lower().startswith("if "):
        return None, text

    remainder = inner_clean[3:]
    if ":" not in remainder:
        return None, text

    condition_part, body_inside = remainder.split(":", 1)
    condition = condition_part.strip()

    trailing = stripped[end:].strip()
    body_tokens = [body_inside.strip(), trailing]
    body = " ".join(token for token in body_tokens if token).strip()
    return condition, body


class ParamAllocator:
    def __init__(self, block_slug: str, block_title: str, overrides: ParamOverrides) -> None:
        self.block_slug = block_slug
        self.block_title = block_title
        self.overrides = overrides
        self.params: OrderedDict[str, ParamSpec] = OrderedDict()
        self.field_count = 0
        self.fallback_count = 1

    def _override_name(self, bracket_literal: str) -> str | None:
        key = (self.block_slug, self.field_count)
        if key in self.overrides.by_slug_ordinal:
            return self.overrides.by_slug_ordinal[key]

        key2 = (self.block_slug, bracket_literal)
        if key2 in self.overrides.by_slug_bracket:
            return self.overrides.by_slug_bracket[key2]

        if bracket_literal in self.overrides.by_bracket:
            return self.overrides.by_bracket[bracket_literal]

        return None

    def _next_fallback(self) -> str:
        value = f"field_{self.fallback_count:02d}"
        self.fallback_count += 1
        return value

    def _dedupe(self, base: str) -> str:
        candidate = _normalize_param_name(base)
        if candidate not in self.params:
            return candidate

        suffix = 2
        while True:
            test = f"{candidate}_{suffix}"
            if test not in self.params:
                return test
            suffix += 1

    def allocate(
        self,
        *,
        bracket_literal: str,
        field_kind: str,
        options: list[str],
        explicit_blank: bool,
        context_before: str,
        context_after: str,
        paragraph_text: str,
        conditional: bool = False,
        condition_label: str | None = None,
    ) -> str:
        self.field_count += 1

        if conditional:
            label = condition_label or "condition"
            base = f"if_{slugify(label)}"
            chosen = self._dedupe(base)
            self.params[chosen] = ParamSpec(
                name=chosen,
                kind="bool",
                explicit_blank=False,
                label=f"Condition: {label}",
            )
            return chosen

        override = self._override_name(bracket_literal)
        if override:
            chosen = self._dedupe(override)
        else:
            base = ""
            context_hint = _heuristic_from_context(context_before, context_after, paragraph_text)
            if context_hint:
                base = context_hint

            if not base:
                inner = bracket_literal[1:-1]
                kind, _, _ = classify_field(inner)
                if kind == "blank":
                    base = _clean_candidate_name(inner)
                else:
                    base = _clean_candidate_name(options[0] if options else inner)

            if base and not _is_reasonable_param_base(base):
                base = ""

            if not base:
                base = self._next_fallback()

            if field_kind == "bool":
                if not base.endswith("_flag") and not base.endswith("_used"):
                    if base in {"yes", "no"}:
                        base = self._next_fallback()
                    elif base.startswith("if_"):
                        base = base[3:]
                    if not base.endswith("_flag"):
                        base = f"{base}_flag"

            chosen = self._dedupe(base)

        self.params[chosen] = ParamSpec(
            name=chosen,
            kind="bool" if field_kind == "bool" else "string",
            explicit_blank=explicit_blank,
            label=_human_label(bracket_literal),
        )
        return chosen


def _emit_field_expression(field_kind: str, param_name: str, options: list[str], bracket_literal: str) -> str:
    fallback = _escape_single_quotes(bracket_literal)
    if field_kind == "bool" and len(options) == 2:
        true_value, false_value = _bool_true_false(options)
        t_escaped = _escape_single_quotes(true_value)
        f_escaped = _escape_single_quotes(false_value)
        return (
            "{{ "
            f"'{t_escaped}' if {param_name} is true else ('{f_escaped}' if {param_name} is false else '{fallback}')"
            " }}"
        )

    return (
        "{{ "
        f"{param_name} if ({param_name} is not none and {param_name} != '') else '{fallback}'"
        " }}"
    )


def _render_paragraph_with_fields(
    text: str,
    allocator: ParamAllocator,
) -> tuple[str, list[AdaptiveField]]:
    spans = _iter_top_level_brackets(text)
    if not spans:
        return text, []

    pieces: list[str] = []
    fields: list[AdaptiveField] = []
    cursor = 0

    for start, end, inner in spans:
        pieces.append(text[cursor:start])
        bracket_literal = text[start:end]
        kind, options, explicit_blank = classify_field(inner)

        context_before = text[:start]
        context_after = text[end:]

        param_name = allocator.allocate(
            bracket_literal=bracket_literal,
            field_kind=kind,
            options=options,
            explicit_blank=explicit_blank,
            context_before=context_before,
            context_after=context_after,
            paragraph_text=text,
        )

        expression = _emit_field_expression(kind, param_name, options, bracket_literal)
        pieces.append(expression)

        fields.append(
            AdaptiveField(
                raw=inner,
                kind=kind,
                options=options,
                explicit_blank=explicit_blank,
                param_name=param_name,
            )
        )
        cursor = end

    pieces.append(text[cursor:])
    return "".join(pieces), fields


def extract_docx_paragraphs(docx_path: Path) -> list[DocParagraph]:
    if not docx_path.exists():
        raise FileNotFoundError(
            "Missing DOCX source at "
            f"{docx_path}. Place the file at data/template_sources/IP_Comprehensive_Adaptive_Templates.docx"
        )

    ns = {"w": "http://schemas.openxmlformats.org/wordprocessingml/2006/main"}
    w_ns = ns["w"]

    with ZipFile(docx_path) as archive:
        try:
            document_xml = archive.read("word/document.xml")
        except KeyError as exc:
            raise CompilerError(f"DOCX missing word/document.xml: {docx_path}") from exc

    root = ET.fromstring(document_xml)

    paragraphs: list[DocParagraph] = []
    for line_no, paragraph in enumerate(root.findall(".//w:body/w:p", ns), start=1):
        parts: list[str] = []
        for element in paragraph.iter():
            if element.tag == f"{{{w_ns}}}t":
                parts.append(element.text or "")
            elif element.tag in {f"{{{w_ns}}}br", f"{{{w_ns}}}cr"}:
                parts.append("\n")
            elif element.tag == f"{{{w_ns}}}tab":
                parts.append("\t")

        text = "".join(parts).replace("\xa0", " ").strip()
        if not text:
            continue

        style: str | None = None
        p_pr = paragraph.find("w:pPr", ns)
        if p_pr is not None:
            style_node = p_pr.find("w:pStyle", ns)
            if style_node is not None:
                style = style_node.attrib.get(f"{{{w_ns}}}val")

        paragraphs.append(DocParagraph(text=text, style=style, line_no=line_no))

    return paragraphs


def _next_nonempty_text(paragraphs: list[DocParagraph], start_idx: int) -> str:
    for idx in range(start_idx, len(paragraphs)):
        candidate = paragraphs[idx].text.strip()
        if candidate:
            return candidate
    return ""


def _is_heading_style(style: str | None, level: int) -> bool:
    if style is None:
        return False
    style_norm = style.lower()
    return style_norm == f"heading{level}".lower()


def _is_pseudo_block_title(text: str, next_text: str) -> bool:
    stripped = text.strip()
    if not stripped.endswith(":"):
        return False
    if stripped.startswith("▸"):
        return False
    if stripped.startswith("["):
        return False
    if len(stripped) > 120:
        return False
    return next_text.lower().startswith("cpt:")


def build_template_ast(paragraphs: list[DocParagraph]) -> list[SectionNode]:
    sections: list[SectionNode] = []
    current_section: SectionNode | None = None
    current_block: TemplateBlock | None = None

    for idx, para in enumerate(paragraphs):
        text = para.text.strip()

        heading1_match = HEADING1_RE.match(text)
        if _is_heading_style(para.style, 1) and heading1_match:
            current_section = SectionNode(
                number=int(heading1_match.group("num")),
                title=heading1_match.group("title").strip(),
            )
            sections.append(current_section)
            current_block = None
            continue

        if current_section is None:
            continue

        heading2_match = HEADING2_RE.match(text)
        if _is_heading_style(para.style, 2):
            current_section.has_heading2 = True
            if heading2_match:
                block_number = heading2_match.group("num")
                title = heading2_match.group("title").strip()
            else:
                block_number = current_section.next_synthetic_number()
                title = text
            current_block = TemplateBlock(
                section_number=current_section.number,
                section_title=current_section.title,
                block_number=block_number,
                title=title,
                category=SECTION_TO_CATEGORY.get(current_section.number, "07_clinical_assessment"),
                source_level=2,
                macro_name="",
                slug="",
            )
            current_section.blocks.append(current_block)
            continue

        if _is_heading_style(para.style, 3):
            current_block = TemplateBlock(
                section_number=current_section.number,
                section_title=current_section.title,
                block_number=current_section.next_synthetic_number(),
                title=text,
                category=SECTION_TO_CATEGORY.get(current_section.number, "07_clinical_assessment"),
                source_level=3,
                macro_name="",
                slug="",
            )
            current_section.blocks.append(current_block)
            continue

        if current_block is None:
            current_block = TemplateBlock(
                section_number=current_section.number,
                section_title=current_section.title,
                block_number=str(current_section.number),
                title=current_section.title,
                category=SECTION_TO_CATEGORY.get(current_section.number, "07_clinical_assessment"),
                source_level=1,
                macro_name="",
                slug="",
            )
            current_section.blocks.append(current_block)

        if not current_section.has_heading2:
            next_text = _next_nonempty_text(paragraphs, idx + 1)
            if _is_pseudo_block_title(text, next_text):
                if current_block.raw_paragraphs:
                    current_block = TemplateBlock(
                        section_number=current_section.number,
                        section_title=current_section.title,
                        block_number=current_section.next_synthetic_number(),
                        title=text.rstrip(":").strip(),
                        category=SECTION_TO_CATEGORY.get(
                            current_section.number, "07_clinical_assessment"
                        ),
                        source_level=2,
                        macro_name="",
                        slug="",
                    )
                    current_section.blocks.append(current_block)
                else:
                    current_block.title = text.rstrip(":").strip()
                    current_block.block_number = current_section.next_synthetic_number()
                continue

        current_block.raw_paragraphs.append(text)

    filtered_sections: list[SectionNode] = []
    for section in sections:
        block_list = [block for block in section.blocks if block.raw_paragraphs]
        if not block_list:
            continue
        section.blocks = block_list
        filtered_sections.append(section)

    for section in filtered_sections:
        for block in section.blocks:
            slug = slugify(f"s{block.section_number}_{block.block_number}_{block.title}")
            block.slug = f"{GENERATED_PREFIX}{slug}"
            block.macro_name = block.slug

    return filtered_sections


def _compile_block_content(block: TemplateBlock, overrides: ParamOverrides) -> None:
    allocator = ParamAllocator(block_slug=block.slug, block_title=block.title, overrides=overrides)

    pending_condition: str | None = None
    nodes: list[ParagraphNode] = []

    for raw_line in block.raw_paragraphs:
        cpt_match = CPT_RE.match(raw_line)
        if cpt_match:
            block.cpt_codes = _parse_cpt_codes(cpt_match.group("value"))
            continue

        if _is_doc_instruction(raw_line):
            block.instruction_notes.append(raw_line.strip())
            continue

        if not raw_line.strip():
            continue

        block.body_lines_raw.append(raw_line)

        condition, inline_body = _extract_condition_prefix(raw_line)
        if condition is not None:
            if inline_body:
                conditional_param = allocator.allocate(
                    bracket_literal=f"[If {condition}:]",
                    field_kind="bool",
                    options=["Yes", "No"],
                    explicit_blank=False,
                    context_before="",
                    context_after="",
                    paragraph_text=raw_line,
                    conditional=True,
                    condition_label=condition,
                )
                rendered, fields = _render_paragraph_with_fields(inline_body, allocator)
                nodes.append(
                    ParagraphNode(
                        source_text=raw_line,
                        rendered_text=rendered,
                        fields=fields,
                        conditional_param=conditional_param,
                    )
                )
                pending_condition = None
            else:
                pending_condition = condition
            continue

        conditional_param: str | None = None
        if pending_condition:
            conditional_param = allocator.allocate(
                bracket_literal=f"[If {pending_condition}:]",
                field_kind="bool",
                options=["Yes", "No"],
                explicit_blank=False,
                context_before="",
                context_after="",
                paragraph_text=raw_line,
                conditional=True,
                condition_label=pending_condition,
            )
            pending_condition = None

        rendered, fields = _render_paragraph_with_fields(raw_line, allocator)
        nodes.append(
            ParagraphNode(
                source_text=raw_line,
                rendered_text=rendered,
                fields=fields,
                conditional_param=conditional_param,
            )
        )

    block.params = list(allocator.params.values())
    block.nodes = nodes


def _block_to_macro_metadata(block: TemplateBlock) -> dict[str, Any]:
    params = [param.name for param in block.params]
    essential = [param.name for param in block.params if param.explicit_blank]
    essential_labels = {
        param.name: param.label for param in block.params if param.explicit_blank and param.label
    }

    metadata: dict[str, Any] = {
        "params": params,
        "defaults": {},
    }

    if block.cpt_codes:
        metadata["cpt"] = " / ".join(block.cpt_codes)

    if essential:
        metadata["required"] = True
        metadata["essential"] = essential
        if essential_labels:
            metadata["essential_labels"] = essential_labels

    if block.instruction_notes:
        metadata["note"] = " | ".join(block.instruction_notes)

    return metadata


def _render_macro(block: TemplateBlock) -> str:
    signature = ""
    if block.params:
        args = [f"{param.name}=none" for param in block.params]
        signature = ", ".join(args)

    cpt_label = ", ".join(block.cpt_codes) if block.cpt_codes else "none"

    lines: list[str] = [
        f"{{# --- [{block.block_number}] {block.title} (CPT: {cpt_label}) --- #}}",
        f"{{% macro {block.macro_name}({signature}) %}}" if signature else f"{{% macro {block.macro_name}() %}}",
    ]

    for idx, node in enumerate(block.nodes):
        if idx > 0:
            lines.append("")
        if node.conditional_param:
            lines.append(f"{{% if {node.conditional_param} %}}")
            lines.append(node.rendered_text)
            lines.append("{% endif %}")
        else:
            lines.append(node.rendered_text)

    lines.append("{% endmacro %}")
    return "\n".join(lines).rstrip() + "\n"


def _section_to_addon_category(section: SectionNode) -> str:
    return section.title.upper()


def _is_macro_candidate(block: TemplateBlock) -> bool:
    section_no = block.section_number
    title_lower = block.title.lower()

    if section_no in MACRO_PREFERRED_SECTIONS:
        return True

    if section_no == 1 and "pre-anesthesia assessment" in title_lower:
        return True

    if section_no == 15 and "post-blvr" in title_lower:
        return True

    if block.cpt_codes and section_no in {1, 2, 3, 14, 15}:
        return True

    return False


def compile_sections(sections: list[SectionNode], overrides: ParamOverrides) -> CompilePlan:
    for section in sections:
        for block in section.blocks:
            _compile_block_content(block, overrides)

    macro_blocks: list[TemplateBlock] = []
    addon_blocks: list[TemplateBlock] = []

    for section in sections:
        for block in section.blocks:
            if not block.nodes and not block.body_lines_raw:
                continue
            if _is_macro_candidate(block):
                macro_blocks.append(block)
            else:
                addon_blocks.append(block)

    macro_blocks.sort(key=lambda block: (block.category, block.sort_key(), block.macro_name))
    addon_blocks.sort(key=lambda block: (block.section_number, block.sort_key(), block.slug))

    return CompilePlan(sections=sections, macro_blocks=macro_blocks, addon_blocks=addon_blocks)


def _replace_autogen_region(existing_text: str, generated_text: str) -> str:
    generated_body = generated_text.rstrip("\n")
    region = f"{AUTOGEN_START}\n{generated_body}\n{AUTOGEN_END}\n"

    if AUTOGEN_START in existing_text and AUTOGEN_END in existing_text:
        pattern = re.compile(
            rf"{re.escape(AUTOGEN_START)}.*?{re.escape(AUTOGEN_END)}\n?",
            flags=re.DOTALL,
        )
        updated = pattern.sub(region, existing_text, count=1)
        return updated

    base = existing_text.rstrip("\n")
    return f"{base}\n\n{region}"


def _merge_schema(
    schema_path: Path,
    generated_macro_meta: dict[str, dict[str, dict[str, Any]]],
) -> str:
    existing = json.loads(schema_path.read_text(encoding="utf-8"))
    if not isinstance(existing, dict):
        existing = {}

    categories = existing.get("categories")
    if not isinstance(categories, dict):
        categories = {}
    existing["categories"] = categories

    for category_key in CATEGORY_FILE_MAP:
        category_payload = categories.get(category_key)
        if not isinstance(category_payload, dict):
            category_payload = {
                "description": CATEGORY_DESCRIPTIONS.get(category_key, category_key),
                "macros": {},
            }
            categories[category_key] = category_payload

        if "description" not in category_payload:
            category_payload["description"] = CATEGORY_DESCRIPTIONS.get(category_key, category_key)

        macros = category_payload.get("macros")
        if not isinstance(macros, dict):
            macros = {}

        kept: OrderedDict[str, Any] = OrderedDict()
        for name, meta in macros.items():
            if isinstance(name, str) and name.startswith(GENERATED_PREFIX):
                continue
            kept[name] = meta

        generated_for_category = generated_macro_meta.get(category_key, {})
        for name in sorted(generated_for_category):
            kept[name] = generated_for_category[name]

        category_payload["macros"] = dict(kept)

    return json.dumps(existing, indent=2, ensure_ascii=False) + "\n"


def _merge_addons(
    addons_path: Path,
    generated_addons: list[dict[str, Any]],
    source_name: str,
) -> str:
    existing_raw = json.loads(addons_path.read_text(encoding="utf-8"))
    if not isinstance(existing_raw, dict):
        existing_raw = {}

    templates = existing_raw.get("templates")
    if not isinstance(templates, list):
        templates = []

    kept_templates: list[dict[str, Any]] = []
    for item in templates:
        if not isinstance(item, dict):
            continue
        slug = item.get("slug")
        if isinstance(slug, str) and slug.startswith(GENERATED_PREFIX):
            continue
        kept_templates.append(item)

    merged_templates = kept_templates + generated_addons

    existing_categories = existing_raw.get("categories")
    category_order: list[str] = []
    seen: set[str] = set()
    if isinstance(existing_categories, list):
        for category in existing_categories:
            if isinstance(category, str) and category and category not in seen:
                seen.add(category)
                category_order.append(category)

    for template in merged_templates:
        category = template.get("category")
        if isinstance(category, str) and category and category not in seen:
            seen.add(category)
            category_order.append(category)

    payload: dict[str, Any] = {
        "source_file": source_name,
        "template_count": len(merged_templates),
        "categories": category_order,
        "templates": merged_templates,
    }

    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def _plan_output_updates(
    *,
    repo_root: Path,
    plan: CompilePlan,
    schema_path: Path,
    addons_path: Path,
    source_name: str,
) -> dict[Path, str]:
    macro_dir = repo_root / "app" / "reporting" / "templates" / "macros"

    by_category_macros: dict[str, list[TemplateBlock]] = {key: [] for key in CATEGORY_FILE_MAP}
    generated_macro_meta: dict[str, dict[str, dict[str, Any]]] = {key: {} for key in CATEGORY_FILE_MAP}

    for block in plan.macro_blocks:
        by_category_macros.setdefault(block.category, []).append(block)
        generated_macro_meta.setdefault(block.category, {})[block.macro_name] = _block_to_macro_metadata(
            block
        )

    updates: dict[Path, str] = {}

    for category, filename in CATEGORY_FILE_MAP.items():
        file_path = macro_dir / filename
        current = file_path.read_text(encoding="utf-8")

        macros = by_category_macros.get(category, [])
        rendered = "\n\n".join(_render_macro(block).rstrip("\n") for block in macros).rstrip("\n")
        patched = _replace_autogen_region(current, rendered)
        if patched != current:
            updates[file_path] = patched

    schema_text = _merge_schema(schema_path, generated_macro_meta)
    current_schema = schema_path.read_text(encoding="utf-8")
    if schema_text != current_schema:
        updates[schema_path] = schema_text

    generated_addons: list[dict[str, Any]] = []
    section_lookup = {section.number: section for section in plan.sections}
    for block in plan.addon_blocks:
        section = section_lookup.get(block.section_number)
        category = _section_to_addon_category(section) if section else "UNCATEGORIZED"
        body = "\n".join(block.body_lines_raw).strip()
        if not body:
            continue
        generated_addons.append(
            {
                "slug": block.slug,
                "title": f"[{block.block_number}] {block.title}",
                "category": category,
                "cpt_codes": block.cpt_codes,
                "params": [param.name for param in block.params],
                "body": body,
            }
        )

    generated_addons.sort(key=lambda item: str(item.get("slug", "")))

    addons_text = _merge_addons(addons_path, generated_addons, source_name=source_name)
    current_addons = addons_path.read_text(encoding="utf-8")
    if addons_text != current_addons:
        updates[addons_path] = addons_text

    return updates


def _write_debug_artifacts(emit_dir: Path, paragraphs: list[DocParagraph], plan: CompilePlan) -> None:
    emit_dir.mkdir(parents=True, exist_ok=True)

    paragraphs_payload = [asdict(item) for item in paragraphs]
    (emit_dir / "paragraphs.json").write_text(
        json.dumps(paragraphs_payload, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )

    ast_payload: list[dict[str, Any]] = []
    for section in plan.sections:
        section_item = {
            "number": section.number,
            "title": section.title,
            "blocks": [],
        }
        for block in section.blocks:
            block_item = {
                "block_number": block.block_number,
                "title": block.title,
                "category": block.category,
                "macro_name": block.macro_name,
                "slug": block.slug,
                "cpt_codes": block.cpt_codes,
                "instruction_notes": block.instruction_notes,
                "params": [asdict(param) for param in block.params],
                "nodes": [
                    {
                        "source_text": node.source_text,
                        "rendered_text": node.rendered_text,
                        "conditional_param": node.conditional_param,
                        "fields": [asdict(field) for field in node.fields],
                    }
                    for node in block.nodes
                ],
            }
            section_item["blocks"].append(block_item)
        ast_payload.append(section_item)

    (emit_dir / "ast.json").write_text(
        json.dumps(ast_payload, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )


def compile_ip_adaptive_templates(
    *,
    input_docx: Path,
    repo_root: Path,
    schema_path: Path,
    addons_path: Path,
    overrides_path: Path,
    write: bool,
    check: bool,
    emit_dir: Path | None = None,
    paragraph_stream: list[DocParagraph] | None = None,
) -> CompileResult:
    if write and check:
        raise CompilerError("--write and --check are mutually exclusive")

    if paragraph_stream is None:
        paragraphs = extract_docx_paragraphs(input_docx)
    else:
        paragraphs = paragraph_stream

    sections = build_template_ast(paragraphs)
    overrides = load_param_overrides(overrides_path)
    plan = compile_sections(sections, overrides)

    updates = _plan_output_updates(
        repo_root=repo_root,
        plan=plan,
        schema_path=schema_path,
        addons_path=addons_path,
        source_name=input_docx.name,
    )

    if emit_dir is not None:
        _write_debug_artifacts(emit_dir, paragraphs, plan)

    changed_paths = sorted(updates.keys())

    if write:
        for path, content in updates.items():
            path.write_text(content, encoding="utf-8")

    if check and updates:
        raise CompilerError(
            "Template compilation would modify files:\n"
            + "\n".join(f"- {path}" for path in changed_paths)
        )

    return CompileResult(
        changed_files=changed_paths,
        generated_macro_count=len(plan.macro_blocks),
        generated_addon_count=len(plan.addon_blocks),
        planned_changes=updates,
    )


def default_paths(repo_root: Path) -> dict[str, Path]:
    return {
        "schema_path": repo_root / "app" / "reporting" / "templates" / "macros" / "template_schema.json",
        "addons_path": repo_root / "data" / "knowledge" / "ip_addon_templates_parsed.json",
        "overrides_path": repo_root / "ops" / "tools" / "template_compiler" / "param_overrides.yaml",
    }
