from __future__ import annotations

import json
from pathlib import Path

from ops.tools.template_compiler.compiler import (
    CATEGORY_FILE_MAP,
    DocParagraph,
    classify_field,
    compile_ip_adaptive_templates,
)


def _init_repo_layout(repo_root: Path) -> tuple[Path, Path, Path]:
    macro_dir = repo_root / "app" / "reporting" / "templates" / "macros"
    macro_dir.mkdir(parents=True, exist_ok=True)

    for filename in CATEGORY_FILE_MAP.values():
        (macro_dir / filename).write_text(
            "{# manual region #}\n{% macro existing_manual() %}manual{% endmacro %}\n",
            encoding="utf-8",
        )

    schema_path = macro_dir / "template_schema.json"
    categories = {
        category: {"description": category, "macros": {}}
        for category in CATEGORY_FILE_MAP
    }
    schema_path.write_text(
        json.dumps(
            {
                "template_system": "test",
                "version": "1",
                "category_macros": {},
                "categories": categories,
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )

    addons_path = repo_root / "data" / "knowledge" / "ip_addon_templates_parsed.json"
    addons_path.parent.mkdir(parents=True, exist_ok=True)
    addons_path.write_text(
        json.dumps(
            {
                "source_file": "seed.json",
                "template_count": 0,
                "categories": [],
                "templates": [],
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )

    overrides_path = repo_root / "ops" / "tools" / "template_compiler" / "param_overrides.yaml"
    overrides_path.parent.mkdir(parents=True, exist_ok=True)
    overrides_path.write_text("{}\n", encoding="utf-8")

    return schema_path, addons_path, overrides_path


def _sample_paragraphs() -> list[DocParagraph]:
    return [
        DocParagraph(text="11. Pleural Procedures", style="Heading1", line_no=1),
        DocParagraph(text="11.2 Thoracentesis", style="Heading2", line_no=2),
        DocParagraph(text="CPT: 32555", style=None, line_no=3),
        DocParagraph(
            text="The [right / left] hemithorax [has / has not] loculations with volume [____] mL.",
            style=None,
            line_no=4,
        ),
        DocParagraph(text="[If LMA:]", style=None, line_no=5),
        DocParagraph(text="Airway access was through [mouth / tracheostomy tube].", style=None, line_no=6),
        DocParagraph(
            text="▸ Document: this should not appear in rendered macro body.",
            style=None,
            line_no=7,
        ),
    ]


def test_field_classification_variants() -> None:
    assert classify_field("right / left")[0] == "enum"
    assert classify_field("has / has not")[0] == "bool"
    assert classify_field("____")[0] == "blank"


def test_compiler_emits_macro_schema_and_instruction_suppression(tmp_path: Path) -> None:
    schema_path, addons_path, overrides_path = _init_repo_layout(tmp_path)

    result = compile_ip_adaptive_templates(
        input_docx=tmp_path / "input.docx",
        repo_root=tmp_path,
        schema_path=schema_path,
        addons_path=addons_path,
        overrides_path=overrides_path,
        write=True,
        check=False,
        paragraph_stream=_sample_paragraphs(),
    )

    assert result.generated_macro_count == 1
    pleural_path = tmp_path / "app" / "reporting" / "templates" / "macros" / "05_pleural.j2"
    pleural_content = pleural_path.read_text(encoding="utf-8")

    assert "BEGIN AUTOGENERATED: ip_adaptive_templates_docx" in pleural_content
    assert "ip_adaptive_" in pleural_content
    assert "{% if if_lma %}" in pleural_content
    assert "[right / left]" in pleural_content
    assert "this should not appear in rendered macro body" not in pleural_content

    schema = json.loads(schema_path.read_text(encoding="utf-8"))
    generated_macros = schema["categories"]["05_pleural"]["macros"]
    generated_keys = [key for key in generated_macros if key.startswith("ip_adaptive_")]
    assert len(generated_keys) == 1

    macro_meta = generated_macros[generated_keys[0]]
    assert macro_meta["cpt"] == "32555"
    assert any(name.startswith("if_lma") for name in macro_meta["params"])
    assert "essential" in macro_meta


def test_compiler_idempotent_on_second_write(tmp_path: Path) -> None:
    schema_path, addons_path, overrides_path = _init_repo_layout(tmp_path)

    first = compile_ip_adaptive_templates(
        input_docx=tmp_path / "input.docx",
        repo_root=tmp_path,
        schema_path=schema_path,
        addons_path=addons_path,
        overrides_path=overrides_path,
        write=True,
        check=False,
        paragraph_stream=_sample_paragraphs(),
    )
    assert first.changed_files

    second = compile_ip_adaptive_templates(
        input_docx=tmp_path / "input.docx",
        repo_root=tmp_path,
        schema_path=schema_path,
        addons_path=addons_path,
        overrides_path=overrides_path,
        write=True,
        check=False,
        paragraph_stream=_sample_paragraphs(),
    )

    assert second.changed_files == []
